CREATE TABLE IF NOT EXISTS raw_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source_ts TEXT NULL,
    record_key VARCHAR(255) NOT NULL,
    station_id VARCHAR(255) NULL,
    charger_id VARCHAR(255) NULL,
    connector_id VARCHAR(255) NULL,
    status VARCHAR(255) NULL,
    message_type VARCHAR(255) NULL,
    payload_sha1 VARCHAR(40) NOT NULL,
    payload_json JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_raw_events_received_at ON raw_events (received_at);
CREATE INDEX IF NOT EXISTS idx_raw_events_source_ts ON raw_events (source_ts);
CREATE INDEX IF NOT EXISTS idx_raw_events_record_key ON raw_events (record_key);
CREATE INDEX IF NOT EXISTS idx_raw_events_status ON raw_events (status);
CREATE INDEX IF NOT EXISTS idx_raw_events_message_type ON raw_events (message_type);
CREATE INDEX IF NOT EXISTS idx_raw_events_payload_sha1 ON raw_events (payload_sha1);
CREATE INDEX IF NOT EXISTS idx_raw_events_payload_json_gin ON raw_events USING GIN (payload_json);

CREATE TABLE IF NOT EXISTS current_status (
    record_key VARCHAR(255) PRIMARY KEY,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source_ts TEXT NULL,
    station_id VARCHAR(255) NULL,
    charger_id VARCHAR(255) NULL,
    connector_id VARCHAR(255) NULL,
    status VARCHAR(255) NULL,
    message_type VARCHAR(255) NULL,
    payload_sha1 VARCHAR(40) NOT NULL,
    payload_json JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_current_status_updated_at ON current_status (updated_at);
CREATE INDEX IF NOT EXISTS idx_current_status_status ON current_status (status);
CREATE INDEX IF NOT EXISTS idx_current_status_payload_json_gin ON current_status USING GIN (payload_json);

CREATE TABLE IF NOT EXISTS snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_ts TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    record_key VARCHAR(255) NOT NULL,
    source_ts TEXT NULL,
    station_id VARCHAR(255) NULL,
    charger_id VARCHAR(255) NULL,
    connector_id VARCHAR(255) NULL,
    status VARCHAR(255) NULL,
    message_type VARCHAR(255) NULL,
    payload_sha1 VARCHAR(40) NOT NULL,
    payload_json JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_snapshots_snapshot_ts ON snapshots (snapshot_ts);
CREATE INDEX IF NOT EXISTS idx_snapshots_record_key ON snapshots (record_key);
CREATE INDEX IF NOT EXISTS idx_snapshots_status ON snapshots (status);
CREATE INDEX IF NOT EXISTS idx_snapshots_payload_json_gin ON snapshots USING GIN (payload_json);
